# Generated by Django 6.0.4 on 2026-04-24 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sermons', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sermon',
            name='video_url',
        ),
        migrations.AddField(
            model_name='sermon',
            name='facebook_url',
            field=models.URLField(blank=True, help_text='Paste the full Facebook video URL e.g. https://www.facebook.com/watch?v=XXXXX', verbose_name='Facebook Link'),
        ),
        migrations.AddField(
            model_name='sermon',
            name='youtube_url',
            field=models.URLField(blank=True, help_text='Paste the full YouTube video URL e.g. https://www.youtube.com/watch?v=XXXXX', verbose_name='YouTube Link'),
        ),
    ]
