# Generated by Django 6.0.4 on 2026-04-20 19:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OfferingReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('service_type', models.CharField(choices=[('sunday_first', 'Sunday 1st Service'), ('sunday_second', 'Sunday 2nd Service'), ('sunday_evening', 'Sunday Evening Service'), ('wednesday', 'Wednesday Service'), ('friday', 'Friday Service'), ('special', 'Special Service / Harambee'), ('other', 'Other')], max_length=30)),
                ('currency', models.CharField(default='KES', max_length=5)),
                ('general_offering', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('thanksgiving_offering', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('special_offering', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('special_offering_purpose', models.CharField(blank=True, max_length=200)),
                ('building_fund', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tithes_cash', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tithes_mpesa', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('missions_offering', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('sunday_school_offering', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('counted_by', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_offerings', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_offerings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='SpiritualProgramReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_type', models.CharField(choices=[('choir', 'Choir'), ('praise_worship', 'Praise & Worship'), ('drama', 'Drama Ministry'), ('intercessory', 'Intercessory Prayer'), ('evangelism', 'Evangelism Team'), ('bible_study', 'Bible Study Group'), ('other', 'Other')], max_length=30)),
                ('date', models.DateField()),
                ('title', models.CharField(max_length=200)),
                ('members_present', models.PositiveIntegerField(default=0)),
                ('total_members', models.PositiveIntegerField(default=0)),
                ('activity_summary', models.TextField()),
                ('achievements', models.TextField(blank=True)),
                ('prayer_items', models.TextField(blank=True)),
                ('upcoming_plans', models.TextField(blank=True)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('leader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_programs', to=settings.AUTH_USER_MODEL)),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_programs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='SundaySchoolReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('lesson_topic', models.CharField(max_length=200)),
                ('scripture_text', models.CharField(blank=True, max_length=200)),
                ('nursery_class', models.PositiveIntegerField(default=0, verbose_name='Nursery (0–3 yrs)')),
                ('junior_class', models.PositiveIntegerField(default=0, verbose_name='Junior (4–8 yrs)')),
                ('middle_class', models.PositiveIntegerField(default=0, verbose_name='Middle (9–12 yrs)')),
                ('senior_class', models.PositiveIntegerField(default=0, verbose_name='Senior (13–17 yrs)')),
                ('teachers_present', models.PositiveIntegerField(default=0)),
                ('memory_verse', models.CharField(blank=True, max_length=300)),
                ('lesson_summary', models.TextField(blank=True)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_sunday_school', to=settings.AUTH_USER_MODEL)),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='taught_sunday_school', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('service_type', models.CharField(choices=[('sunday_first', 'Sunday 1st Service'), ('sunday_second', 'Sunday 2nd Service'), ('sunday_evening', 'Sunday Evening Service'), ('wednesday', 'Wednesday Bible Study'), ('friday', 'Friday Prayer Meeting'), ('special', 'Special Service'), ('other', 'Other')], max_length=30)),
                ('total_attendance', models.PositiveIntegerField(default=0)),
                ('men', models.PositiveIntegerField(default=0)),
                ('women', models.PositiveIntegerField(default=0)),
                ('youth', models.PositiveIntegerField(default=0)),
                ('children', models.PositiveIntegerField(default=0)),
                ('visitors', models.PositiveIntegerField(default=0)),
                ('new_converts', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('presiding_minister', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='presided_services', to=settings.AUTH_USER_MODEL)),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_attendance', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('date', 'service_type')},
            },
        ),
    ]
